services:
  netpulse:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./runtime:/app/runtime

  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - netpulse
