frr defaults datacenter
hostname r2
!
interface lo
 ip ospf passive
exit
!
interface lnk1
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf cost 10
exit
!
interface lnk2
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf cost 10
exit
!
router ospf
 ospf router-id 10.255.0.2
 network 10.0.1.0/24 area 0
 network 10.0.2.0/24 area 0
 network 10.255.0.2/32 area 0
 maximum-paths 8
exit
!
